server:
  port: 8081
spring:
  application:
    name: cloud-grpc-client
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
grpc:
  server:
    port: 6565
  client:
    cloud-grpc-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
