// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloServer.proto

package net.devh.boot.grpc.examples.lib;

public interface HelloTwoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloTwoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MetaData metadata = 1;</code>
   */
  boolean hasMetadata();
  /**
   * <code>.MetaData metadata = 1;</code>
   */
  net.devh.boot.grpc.examples.lib.MetaData getMetadata();
  /**
   * <code>.MetaData metadata = 1;</code>
   */
  net.devh.boot.grpc.examples.lib.MetaDataOrBuilder getMetadataOrBuilder();

  /**
   * <code>.File file = 2;</code>
   */
  boolean hasFile();
  /**
   * <code>.File file = 2;</code>
   */
  net.devh.boot.grpc.examples.lib.File getFile();
  /**
   * <code>.File file = 2;</code>
   */
  net.devh.boot.grpc.examples.lib.FileOrBuilder getFileOrBuilder();

  public net.devh.boot.grpc.examples.lib.HelloTwoRequest.RequestCase getRequestCase();
}
