// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package net.devh.boot.grpc.examples.lib;

public interface MapFieldEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MapFieldEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool result = 2;</code>
   */
  boolean getResult();
}
