// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUpload.proto

package net.devh.boot.grpc.examples.lib;

public interface FileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:File)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   */
  com.google.protobuf.ByteString getContent();
}
