// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package net.devh.boot.grpc.examples.lib;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MapFieldEntry result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>.MapFieldEntry result = 1;</code>
   */
  net.devh.boot.grpc.examples.lib.MapFieldEntry getResult();
  /**
   * <code>.MapFieldEntry result = 1;</code>
   */
  net.devh.boot.grpc.examples.lib.MapFieldEntryOrBuilder getResultOrBuilder();
}
