// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUpload.proto

package net.devh.boot.grpc.examples.lib;

public interface HelloTwoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloTwoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 2;</code>
   */
  net.devh.boot.grpc.examples.lib.Status getStatus();
}
